import breathe_1 from 'assets/gif/breathe_1.gif'
import breathe_2 from 'assets/gif/breathe_2.gif'
import breathe_3 from 'assets/gif/breathe_3.gif'
import color_1 from 'assets/gif/color_1.gif'
import color_2 from 'assets/gif/color_2.gif'
import flow_1 from 'assets/gif/flow_1.gif'
import flow_2 from 'assets/gif/flow_2.gif'
import flow_3 from 'assets/gif/flow_3.gif'
import frow_1 from 'assets/gif/frow_1.gif'
import frow_2 from 'assets/gif/frow_2.gif'
import frow_3 from 'assets/gif/frow_3.gif'
import liquid_1 from 'assets/gif/liquid_1.gif'
import liquid_2 from 'assets/gif/liquid_2.gif'
import liquid_3 from 'assets/gif/liquid_3.gif'
import misc_1 from 'assets/gif/misc_1.gif'
import misc_2 from 'assets/gif/misc_2.gif'
import misc_3 from 'assets/gif/misc_3.gif'
import misc_4 from 'assets/gif/misc_4.gif'
import misc_5 from 'assets/gif/misc_5.gif'
import newton_1 from 'assets/gif/newton_1.gif'
import newton_2 from 'assets/gif/newton_2.gif'
import roll_1 from 'assets/gif/roll_1.gif'
import roll_2 from 'assets/gif/roll_2.gif'
import sand_1 from 'assets/gif/sand_1.gif'
import sand_2 from 'assets/gif/sand_2.gif'
import sand_3 from 'assets/gif/sand_3.gif'
import split_1 from 'assets/gif/split_1.gif'
import split_2 from 'assets/gif/split_2.gif'
import split_3 from 'assets/gif/split_3.gif'
import transform_1 from 'assets/gif/transform_1.gif'
import transform_2 from 'assets/gif/transform_2.gif'
import transform_3 from 'assets/gif/transform_3.gif'

let gifs = [breathe_1, breathe_2, breathe_3, color_1, color_2, flow_1, flow_2, flow_3, frow_1, frow_2, frow_3, liquid_1, liquid_2, liquid_3, misc_1, misc_2, misc_3, misc_4, misc_5, newton_1, newton_2, roll_1, roll_2, sand_1, sand_2, sand_3, split_1, split_2, split_3, transform_1, transform_2, transform_3]

export {gifs};